name: Playwright-Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  all:
    runs-on: ubuntu-latest
    name: Build & Test
    env:
      MIX_ENV: test
      PLAYWRIGHT_TRANSPORT: driver
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.4'
        otp-version: '28.0.4'
    - name: Install Elixir dependencies
      run: mix deps.get
    - name: Install Playwright dependencies (e.g., browsers)
      run: mix playwright.install
    # NOTE: not needed for now, while assets are
    #       directly installed to `priv/static`.
    # - name: Install Node dependencies
    #   run: npm install --prefix assets
    - name: Run tests
      run: mix test
